spring:
  application:
    name: dubbo-provider
dubbo:
  scan:
    base-packages: jx.sun.springboot.dubbo
  application:
    name: dubbo-provider
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://localhost:2181
